import { ThemeColors, ThemeKey } from '@/lib/types';

export const THEMES: Record<ThemeKey, ThemeColors> = {
  kirby: {
    primary: '#FFD1DC',
    secondary: '#B0E0E6',
    accent: '#FFB7C5',
    background: '#FFF7FA',
    surface: '#FFFFFF',
    surfaceElevated: '#FFF0F5',
    text: '#2D1B2E',
    textSecondary: '#6B4C6E',
    textMuted: '#A889AA',
    border: '#F0D6E8',
    success: '#B8F2E6',
    warning: '#FFF3B0',
    error: '#FFB3BA',
    vaultBg: '#2D1B2E',
    tabBar: '#FFFFFF',
    tabBarActive: '#FFD1DC',
    tabBarInactive: '#C4A0B4',
    cardShadow: 'rgba(255, 143, 171, 0.2)',
    overlay: 'rgba(45, 27, 46, 0.6)',
  },
  dark: {
    primary: '#FF8FAB',
    secondary: '#6DDFC8',
    accent: '#FFB7C5',
    background: '#0D0D12',
    surface: '#1A1A24',
    surfaceElevated: '#22222F',
    text: '#F5EEF8',
    textSecondary: '#C9B8D0',
    textMuted: '#7A6E80',
    border: '#2E2A35',
    success: '#6DDFC8',
    warning: '#FFE08A',
    error: '#FF6B8A',
    vaultBg: '#08080E',
    tabBar: '#1A1A24',
    tabBarActive: '#FF8FAB',
    tabBarInactive: '#5A5060',
    cardShadow: 'rgba(255, 143, 171, 0.15)',
    overlay: 'rgba(0, 0, 0, 0.75)',
  },
  ocean: {
    primary: '#7EC8E3',
    secondary: '#A8D8EA',
    accent: '#B5EAD7',
    background: '#F0F8FF',
    surface: '#FFFFFF',
    surfaceElevated: '#EBF5FB',
    text: '#0A2342',
    textSecondary: '#2E6B8A',
    textMuted: '#7AAFC0',
    border: '#C8E6F0',
    success: '#B5EAD7',
    warning: '#FFE08A',
    error: '#FFB3BA',
    vaultBg: '#0A2342',
    tabBar: '#FFFFFF',
    tabBarActive: '#2E9FC2',
    tabBarInactive: '#8BBCCC',
    cardShadow: 'rgba(46, 159, 194, 0.18)',
    overlay: 'rgba(10, 35, 66, 0.65)',
  },
  forest: {
    primary: '#A8D8A8',
    secondary: '#C8E6C9',
    accent: '#DCEDC8',
    background: '#F5FBF5',
    surface: '#FFFFFF',
    surfaceElevated: '#EBF5EB',
    text: '#1A2E1A',
    textSecondary: '#3D6B3D',
    textMuted: '#7A9E7A',
    border: '#C8DFC8',
    success: '#A8D8A8',
    warning: '#FFF3B0',
    error: '#FFB3BA',
    vaultBg: '#1A2E1A',
    tabBar: '#FFFFFF',
    tabBarActive: '#4CAF50',
    tabBarInactive: '#8ABC8A',
    cardShadow: 'rgba(76, 175, 80, 0.18)',
    overlay: 'rgba(26, 46, 26, 0.65)',
  },
};

export const DEFAULT_SETTINGS = {
  theme: 'kirby' as ThemeKey,
  gridColumns: 2 as 2 | 3,
  roundedCorners: 24,
  shadowIntensity: 6,
  autoPlay: false,
  loopVideos: false,
  defaultMute: true,
  defaultEditorMode: 'edit' as 'edit' | 'preview',
  notesFontSize: 14,
  vaultEnabled: false,
  vaultPin: '',
  autoLockMinutes: 5,
};
