import { MediaEntry } from './types';

export const MOCK_ENTRIES: MediaEntry[] = [
  {
    id: '1',
    title: 'Golden Hour Walk',
    type: 'video',
    notes: '## Golden Hour Walk\n\nThe light was absolutely magical today. That warm amber glow right before sunset made everything look like a painting.\n\n- Found a new trail\n- Met some friendly dogs\n- Stayed until dusk',
    source_link: '',
    thumbnail_url: 'https://images.pexels.com/photos/1612461/pexels-photo-1612461.jpeg?auto=compress&cs=tinysrgb&w=400',
    local_path: '',
    is_vaulted: false,
    tags: ['nature', 'evening'],
    media_date: '2026-04-10',
    duration_seconds: 124,
    file_size_bytes: 85000000,
    created_at: '2026-04-10T18:30:00Z',
    updated_at: '2026-04-10T18:30:00Z',
  },
  {
    id: '2',
    title: 'Coffee Morning Ritual',
    type: 'video',
    notes: '## Morning Ritual\n\nStarted filming my morning coffee routine. There is something deeply meditative about the process.\n\n> "The morning cup of coffee has an exhilaration about it which the cheering influence of the afternoon or evening cup of tea cannot be expected to reproduce."',
    source_link: 'https://mega.nz/file/EXAMPLE123#key456',
    thumbnail_url: 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=400',
    local_path: '',
    is_vaulted: false,
    tags: ['morning', 'coffee'],
    media_date: '2026-04-09',
    duration_seconds: 67,
    file_size_bytes: 45000000,
    created_at: '2026-04-09T08:15:00Z',
    updated_at: '2026-04-09T09:00:00Z',
  },
  {
    id: '3',
    title: 'City Lights at Midnight',
    type: 'video',
    notes: '## City Lights\n\nWent out late to capture the city at its quietest. The reflections on the wet pavement were stunning.',
    source_link: 'https://mega.nz/folder/BIGARCHIVE#keyABC',
    thumbnail_url: 'https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg?auto=compress&cs=tinysrgb&w=400',
    local_path: '',
    is_vaulted: false,
    tags: ['city', 'night'],
    media_date: '2026-04-08',
    duration_seconds: 210,
    file_size_bytes: 1200000000,
    created_at: '2026-04-08T23:45:00Z',
    updated_at: '2026-04-08T23:45:00Z',
  },
  {
    id: '4',
    title: 'Spring Blossoms',
    type: 'image',
    notes: '## Spring Blossoms\n\nThe cherry blossoms are out! Only lasts about two weeks, so I had to capture them.\n\n**Location:** Riverside Park\n**Camera:** Shot on mobile, golden hour',
    source_link: '',
    thumbnail_url: 'https://images.pexels.com/photos/931177/pexels-photo-931177.jpeg?auto=compress&cs=tinysrgb&w=400',
    local_path: '',
    is_vaulted: false,
    tags: ['spring', 'flowers'],
    media_date: '2026-04-07',
    duration_seconds: 0,
    file_size_bytes: 4200000,
    created_at: '2026-04-07T14:20:00Z',
    updated_at: '2026-04-07T14:20:00Z',
  },
  {
    id: '5',
    title: 'Secret Memory',
    type: 'video',
    notes: '## Private Note\n\nThis one is just for me.',
    source_link: '',
    thumbnail_url: 'https://images.pexels.com/photos/3165335/pexels-photo-3165335.jpeg?auto=compress&cs=tinysrgb&w=400',
    local_path: '',
    is_vaulted: true,
    tags: ['private'],
    media_date: '2026-04-06',
    duration_seconds: 45,
    file_size_bytes: 30000000,
    created_at: '2026-04-06T20:00:00Z',
    updated_at: '2026-04-06T20:00:00Z',
  },
  {
    id: '6',
    title: 'Cooking Experiments',
    type: 'video',
    notes: '## Pasta From Scratch\n\nFinally attempted homemade pasta. It took three hours but was absolutely worth it.\n\n### Recipe Notes\n- 2 cups flour\n- 3 eggs\n- Pinch of salt\n\nKey: knead for at least 10 minutes!',
    source_link: '',
    thumbnail_url: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=400',
    local_path: '',
    is_vaulted: false,
    tags: ['food', 'cooking'],
    media_date: '2026-04-05',
    duration_seconds: 340,
    file_size_bytes: 220000000,
    created_at: '2026-04-05T17:00:00Z',
    updated_at: '2026-04-05T18:30:00Z',
  },
  {
    id: '7',
    title: 'Rainy Window Thoughts',
    type: 'image',
    notes: '## On a Rainy Afternoon\n\nThere is something so comforting about rain hitting the window while you are warm inside. Captured this moment to remember the feeling.',
    source_link: '',
    thumbnail_url: 'https://images.pexels.com/photos/110874/pexels-photo-110874.jpeg?auto=compress&cs=tinysrgb&w=400',
    local_path: '',
    is_vaulted: false,
    tags: ['moody', 'rain'],
    media_date: '2026-04-04',
    duration_seconds: 0,
    file_size_bytes: 3100000,
    created_at: '2026-04-04T15:45:00Z',
    updated_at: '2026-04-04T15:45:00Z',
  },
  {
    id: '8',
    title: 'Concert Night',
    type: 'video',
    notes: '## Live Music\n\nFinally saw them live. Front row. Every song felt like the first time.\n\nSetlist highlights:\n- Opening with the classic\n- That unreleased track\n- Incredible encore',
    source_link: 'https://mega.nz/file/CONCERT2026#secretkey',
    thumbnail_url: 'https://images.pexels.com/photos/1540406/pexels-photo-1540406.jpeg?auto=compress&cs=tinysrgb&w=400',
    local_path: '',
    is_vaulted: false,
    tags: ['music', 'concert'],
    media_date: '2026-04-03',
    duration_seconds: 5400,
    file_size_bytes: 48000000000,
    created_at: '2026-04-03T21:00:00Z',
    updated_at: '2026-04-03T23:30:00Z',
  },
  {
    id: '9',
    title: 'Cat Being Adorable',
    type: 'video',
    notes: '## Mochi in the Sunshine\n\nCaught Mochi doing that thing where she sits in the exact spot of sunlight on the floor and just *radiates* contentment.',
    source_link: '',
    thumbnail_url: 'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&w=400',
    local_path: '',
    is_vaulted: false,
    tags: ['cat', 'cute'],
    media_date: '2026-04-02',
    duration_seconds: 32,
    file_size_bytes: 18000000,
    created_at: '2026-04-02T11:30:00Z',
    updated_at: '2026-04-02T11:30:00Z',
  },
  {
    id: '10',
    title: 'Bookshelf Reorganization',
    type: 'image',
    notes: '## The Great Reorganization\n\nSpent a whole Sunday reorganizing books by color and then by vibe. Some people think this is chaos. I think it is art.',
    source_link: '',
    thumbnail_url: 'https://images.pexels.com/photos/1370298/pexels-photo-1370298.jpeg?auto=compress&cs=tinysrgb&w=400',
    local_path: '',
    is_vaulted: false,
    tags: ['books', 'home'],
    media_date: '2026-04-01',
    duration_seconds: 0,
    file_size_bytes: 5600000,
    created_at: '2026-04-01T16:00:00Z',
    updated_at: '2026-04-01T16:00:00Z',
  },
];
